# .streamlit/secrets.toml (Streamlit Cloudで設定する内容)
[users.user_mamo]
username = "mamo"
password_hash = "$2b$12$3ymtgUV9VA8iIPWmHBEJEe.BQzea07FNtulHsdUsvk2LD2.VMumIW"

[users.user_admin]
username = "admin"
password_hash = "$2b$12$kV39vA3/LgPU1wEX53vxh.G8ex5revLaqXJFfPBlISL5MRNoBXBya"

[users.guest]
username = "guest"
password_hash = "$2b$12$BYxembzlx8j7JNL26T./WeeJcI3nwQ1C/U6aQnZ1io0AFWha8jTwy"

# 必要に応じて他のユーザーを追加
